### ISSUE TITLE
Organize similar to the repo.

### ISSUE THREAD

**Issue by Catoptromancy** [freedoom/attic#1]
Instead of having people's names as the main directories, a listing of directories by resource type would be better. Basically a mirror of the repo. Sounds, Level, Music and such. Then inside those directories we add people's names and the relevant resources. 

It makes browsing so much easier. Look for sprites in a sprite directory, instead of searching every single directory in case there are sprites in there.

**Comment by fragglet** [comment]
I have no objection to this, except to say that some of the stuff is grouped into subdirectories and I'd like to keep that grouping. So for example, espi/shotgun should be moved to sprites/espi/shotgun, not just all dumped into sprites/espi with no organization.

In some cases this is actually essential to do: see espi/startan_textures_1 vs. espi/startan_textures_2 for example. But it's nice to keep things conceptually separate anyway: I actually wish the Freedoom repository was organized in the same way.

**Comment by Xindage** [comment]
do you guys have any opinion in my PR #14 i'm waiting an approval about it, it's not exactly like fraggle wanted, but my txt file provide all the necessary info.

**Comment by GeorgePieVG** [comment]
Done in [this PR](https://github.com/freedoom/attic/pull/20)

**Comment by Xindage** [comment]
This is done by #20 and #22
