### ISSUE TITLE
Old resources which haven't been added yet

### ISSUE THREAD

**Issue by Talon1024** [freedoom/attic#12]
I have a bunch of resources from the old Freedoom, which haven't been added to the attic yet.

Crate textures:
![bcratel1](https://user-images.githubusercontent.com/6550500/37495607-601c3e90-2884-11e8-9356-4bd4da1dbda0.png)
![bcrater1](https://user-images.githubusercontent.com/6550500/37495641-8370ede6-2884-11e8-8e5c-7e2e2079c902.png)
![cratop1](https://user-images.githubusercontent.com/6550500/37495608-602a904e-2884-11e8-8447-d36958e65ddb.png)
![cratop2](https://user-images.githubusercontent.com/6550500/37495609-603982ac-2884-11e8-8a55-fe9160795c79.png)
![gcratel1](https://user-images.githubusercontent.com/6550500/37495610-60492234-2884-11e8-8b17-f6c4468f962f.png)
![gcrater1](https://user-images.githubusercontent.com/6550500/37495611-605849bc-2884-11e8-8c0d-99cca9c238b8.png)
![bcratem1](https://user-images.githubusercontent.com/6550500/37495646-8b84ff90-2884-11e8-9773-e641589bbdf9.png)
![gcratem1](https://user-images.githubusercontent.com/6550500/37495648-8d735b58-2884-11e8-8371-13e5f67da829.png)

And rock textures which were never added in the first place (by fredrik IIRC):
![rw35_1_b](https://user-images.githubusercontent.com/6550500/37495632-78714f94-2884-11e8-94d0-6d9830e0aa65.png)
![rw35_2_b](https://user-images.githubusercontent.com/6550500/37495633-78819a70-2884-11e8-927d-c46ea87422c3.png)

**Comment by fragglet** [comment]
Please send a PR.

**Comment by Talon1024** [comment]
I don't know who made the crate textures, though, which is why I didn't send a PR.

**Comment by Xindage** [comment]
the only way to know it is finding who did the commit of these files, that can be found revising the GIANT log of freedoom. Even if someone else did the commit like chungy or fraggle, they still put the name of who did the files.
